name: asana-auto-ticket
on: 
  issues:
    types: [opened]

jobs:
  create-asana-ticket:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - run: yarn github-action-asana
        env:
          ASANA_SECRET: ${{ secrets.ASANA_SECRET }}
          ASANA_PROJECT: ${{ secrets.ASANA_PROJECT }}
          ASANA_SECTION: ${{ secrets.ASANA_SECTION }}
          GITHUB_CONTEXT: ${{ toJSON(github) }}